### ISSUE TITLE
IndexError: index 0 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by Jake-He** [stanfordnlp/cocoa#38]
Hi
try to run python src/scripts/generate_scenarios.py --schema-path data/schema.json --scenarios-path data/scenarios.json --num-scenarios 500 --random-attributes --random-items --alphas 0.3 1 3 

I had error:
Traceback (most recent call last):
  File "src/scripts/generate_scenarios.py", line 158, in <module>
    s = generate_scenario(schema)
  File "src/scripts/generate_scenarios.py", line 93, in generate_scenario
    index = random_multinomial(distrib)
  File "/home/ ... /cocoa/src/basic/util.py", line 11, in random_multinomial
    accum += probs[i]
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by hhexiy** [comment]
Hi,

What is the schema file you were using? I'm able to run the command successfully with `data/friends-schema.json`.

**Comment by loveJasmine** [comment]
I got the same error with:


python src/scripts/generate_scenarios.py --schema-path data/schema.json --scenarios-path data/scenarios.json --num-scenarios 500 --random-attributes --random-items --alphas 0.3 1 3

**Comment by hhexiy** [comment]
@loveJasmine are you on the master branch? We've removed `data/schema.json` some time ago; it's outdated.

**Comment by loveJasmine** [comment]
I had update the code, got the same error on

python src/scripts/generate_scenarios.py --schema-path data/schema.json --scenarios-path data/scenarios.json --num-scenarios 500 --random-attributes --random-items --alphas 0.3 1 3

**Comment by hhexiy** [comment]
Can you use but data/friends-schema.json? data/schema.json should not be used.

**Comment by loveJasmine** [comment]
@hhexiy , that works
