### ISSUE TITLE
Scoping issues in template

### ISSUE THREAD

**Issue by skrcode** [stanfordnlp/cocoa#46]
https://github.com/stanfordnlp/cocoa/blob/65d61c714f0bc4a9bf24ad84ad6fc2105f0028bc/src/web/templates/chat.html#L335

This loop iter update does not seem to work, I guess due to scoping issues. A better alternative would be to remove the iterators and use the default {{loop.index}}, as suggested in https://stackoverflow.com/a/7537466

**Comment by hhexiy** [comment]
Thanks for the suggestion! It looks like this line is deprecate code and takes no effect now. So I'm closing this.
