### ISSUE TITLE
What the soulution to ImportError: cannot import name LIWC ?

### ISSUE THREAD

**Issue by ha-lins** [stanfordnlp/cocoa#53]
Hi,He He! 
I've learned a lot from running and reading your code!
However,I meet a problem when i setup the web server i.g. when i python ../scripts/visualize_transcripts.py
I get:

**Traceback (most recent call last):
  File "../scripts/visualize_transcripts.py", line 4, in <module>
    from analysis.visualizer import Visualizer
  File "/data/linshuai/cocoa/craigslistbargain/analysis/visualizer.py", line 8, in <module>
    from analyze_strategy import StrategyAnalyzer
  File "/data/linshuai/cocoa/craigslistbargain/analysis/analyze_strategy.py", line 25, in <module>
    from liwc import LIWC
ImportError: cannot import name LIWC**

i've install the liwc via pip install.However,it doesn't seem to with LIWC.
And i wonder the use of this line of code:
        self.liwc = LIWC.from_pkl(liwc_path)

Appreciating for your help!

**Comment by hhexiy** [comment]
Hi, this is not needed. I've removed the analysis code.
